#define MODEL_Root              0x25
#define MODEL_Books             0x24
#define MODEL_Books             0x23
#define MODEL_BoxTop            0x22
#define MODEL_BoxTop            0x21
#define MODEL_Outside           0x20
#define MODEL_Lantern           0x1F
#define MODEL_Books             0x1E
#define MODEL_BoxFloor          0x1D
#define MODEL_BoxTop            0x1C
#define MODEL_PotsPan           0x1B
#define MODEL_Recipes           0x1A
#define MODEL_Pitchers          0x19
#define MODEL_Photos            0x18
#define MODEL_PhotoShelf        0x17
#define MODEL_Flowers           0x16
#define MODEL_WindowSill        0x15
#define MODEL_OvenTop           0x14
#define MODEL_Oven              0x13
#define MODEL_KitchenCounter    0x12
#define MODEL_BookShelf         0x11
#define MODEL_Storage           0x10
#define MODEL_Plates            0xF
#define MODEL_WindowGlass       0xE
#define MODEL_WindowRod         0xD
#define MODEL_Curtains          0xC
#define MODEL_SeatFrame         0xB
#define MODEL_SeatCushion       0xA
#define MODEL_FrontFloor        0x9
#define MODEL_Carpet            0x8
#define MODEL_Roof              0x7
#define MODEL_WoodParition      0x6
#define MODEL_WallBlue          0x5
#define MODEL_WallGreen         0x4
#define MODEL_FloorKitchen      0x3
#define MODEL_FloorCommon       0x2
#define MODEL_TrimBottom        0x1
#define MODEL_TrimTop           0x0

