#define MODEL_Root              0x38
#define MODEL_Stage             0x37
#define MODEL_BarrelRed         0x36
#define MODEL_BombPile          0x35
#define MODEL_BombBox           0x34
#define MODEL_BarrelBlack       0x33
#define MODEL_SnipingCrate      0x32
#define MODEL_Tunnel            0x31
#define MODEL_BrushBig          0x30
#define MODEL_BrushSmall        0x2F
#define MODEL_GravelFront       0x2E
#define MODEL_GravelMiddle      0x2D
#define MODEL_GravelTop         0x2C
#define MODEL_Hill              0x2B
#define MODEL_Cactus            0x2A
#define MODEL_MountainsShade    0x29
#define MODEL_StageWooden       0x28
#define MODEL_ChompStake        0x27
#define MODEL_ChompConnector    0x26
#define MODEL_KoopaCartTop      0x25
#define MODEL_KoopaCartSides    0x24
#define MODEL_TrainTracksFront  0x23
#define MODEL_TrainTracksTop    0x22
#define MODEL_TrainCarRail      0x21
#define MODEL_TrainCarBase      0x20
#define MODEL_TrainCarTrim      0x1F
#define MODEL_TrainCarWall      0x1E
#define MODEL_TrainCarEntrance  0x1D
#define MODEL_TrainCarRoofFront 0x1C
#define MODEL_TrainCarRoofTop   0x1B
#define MODEL_Wheels            0x1A
#define MODEL_Wheel13Group      0x19
#define MODEL_Wheel13           0x18
#define MODEL_Wheel12Group      0x17
#define MODEL_Wheel12           0x16
#define MODEL_Wheel11Group      0x15
#define MODEL_Wheel11           0x14
#define MODEL_Wheel10Group      0x13
#define MODEL_Wheel10           0x12
#define MODEL_Wheel9Group       0x11
#define MODEL_Wheel9            0x10
#define MODEL_Wheel8Group       0xF
#define MODEL_Wheel8            0xE
#define MODEL_Wheel7Group       0xD
#define MODEL_Wheel7            0xC
#define MODEL_Wheel6Group       0xB
#define MODEL_Wheel6            0xA
#define MODEL_Wheel5Group       0x9
#define MODEL_Wheel5            0x8
#define MODEL_Wheel4Group       0x7
#define MODEL_Wheel4            0x6
#define MODEL_Wheel3Group       0x5
#define MODEL_Wheel3            0x4
#define MODEL_Wheel2Group       0x3
#define MODEL_Wheel2            0x2
#define MODEL_Wheel1Group       0x1
#define MODEL_Wheel1            0x0

