#message:2F:(Misc_BadgeEmblemName) {
	Badge Emblem[End]
}

#message:2F:(Misc_BadgeEmblemFullDesc) {
	Increases maximum BP by 3.[End]
}

#message:2F:(Misc_BadgeEmblemShortDesc) {
	Increases maximum BP by 3.[End]
}

#message:2F:(Misc_BowsersBrother) {
	Bowser?[End]
}

#message:2F:(Misc_BowsersBrotherTattle) {
	[Style right]
	This is Bowser?[Wait][End]
}

#message:2F:(Misc_KingBoo) {
	King Boo[End]
}

#message:2F:(Misc_KingBooTattle) {
	[Style right]
	This is King Boo.[Wait][End]
}

#message:2F:(Misc_Tatanga) {
	Tatanga[End]
}

#message:2F:(Misc_TatangaTattle) {
	[Style right]
	This is Tatanga.[Wait][End]
}

#message:2F:(Misc_Chikako) {
	Chikako[End]
}

#message:2F:(Misc_ChikakoTattle) {
	[Style right]
	This is Chikako.[Wait][End]
}

#message:2F:(Misc_BowserInteract) {
	[Style right]
	[Voice bowser]
	Gwaah ha ha ha ha ha!!!!![BR][Wait][End]
}
