#message:2F:(Misc_BadgeEmblemName) {
	Badge Emblem[End]
}

#message:2F:(Misc_BadgeEmblemFullDesc) {
	Increases maximum BP by 3.[End]
}

#message:2F:(Misc_BadgeEmblemShortDesc) {
	Increases maximum BP by 3.[End]
}

#message:2F:(Misc_GiantChomp) {
	Giant Chomp[End]
}

#message:2F:(Misc_GiantChompTattle) {
	[Style right]
	This is Giant Chomp.[Wait][End]
}

#message:2F:(Misc_FalseBowser) {
	Bowser?[End]
}

#message:2F:(Misc_FalseBowserTattle) {
	[Style right]
	This is Bowser?[Wait][End]
}

#message:2F:(Misc_BowserInteract) {
	[Style right]
	[Voice bowser]
	Gwaah ha ha ha ha ha!!!!![BR][Wait][End]
}
