#message:2F:(Misc_BadgeEmblemName) {
	Badge Emblem[End]
}

#message:2F:(Misc_BadgeEmblemFullDesc) {
	Increases maximum BP by 3.[End]
}

#message:2F:(Misc_BadgeEmblemShortDesc) {
	Increases maximum BP by 3.[End]
}

#message:2F:(Misc_GreenBandit) {
	G Bandit[End]
}

#message:2F:(Misc_GreenBanditTattle) {
	[Style right]
	This is Green Bandit.[Wait][End]
}

#message:2F:(Misc_YellowBandit) {
	Y Bandit[End]
}

#message:2F:(Misc_YellowBanditTattle) {
	[Style right]
	This is Yellow Bandit.[Wait][End]
}

#message:2F:(Misc_BlackBandit) {
	B Bandit[End]
}

#message:2F:(Misc_BlackBanditTattle) {
	[Style right]
	This is Black Bandit.[Wait][End]
}

#message:2F:(Misc_RedBandit) {
	R Bandit[End]
}

#message:2F:(Misc_RedBanditTattle) {
	[Style right]
	This is Red Bandit.[Wait][End]
}

#message:2F:(Misc_GiantChomp) {
	Giant Chomp[End]
}

#message:2F:(Misc_GiantChompTattle) {
	[Style right]
	This is Giant Chomp.[Wait][End]
}

#message:2F:(Misc_FalseBowser) {
	Bowser?[End]
}

#message:2F:(Misc_FalseBowserTattle) {
	[Style right]
	This is Bowser?[Wait][End]
}

#message:2F:(Misc_BowserInteract) {
	[Style right]
	[Voice bowser]
	Gwaah ha ha ha ha ha!!!!![BR][Wait][End]
}
