#message:2F:(Misc_GreenBandit) {
	G Bandit[End]
}

#message:2F:(Misc_GreenBanditTattle) {
	[Style right]
	This is Green Bandit.[Wait][End]
}

#message:2F:(Misc_YellowBandit) {
	Y Bandit[End]
}

#message:2F:(Misc_YellowBanditTattle) {
	[Style right]
	This is Yellow Bandit.[Wait][End]
}

#message:2F:(Misc_BlackBandit) {
	B Bandit[End]
}

#message:2F:(Misc_BlackBanditTattle) {
	[Style right]
	This is Black Bandit.[Wait][End]
}

#message:2F:(Misc_RedBandit) {
	R Bandit[End]
}

#message:2F:(Misc_RedBanditTattle) {
	[Style right]
	This is Red Bandit.[Wait][End]
}

#message:2F:(Misc_BrigaderBones) {
	Brigader Bones[End]
}

#message:2F:(Misc_BrigaderBonesTattle) {
	[Style right]
	This is Brigader Bones.[Wait][End]
}

#message:2F:(Misc_GiantChomp) {
	Giant Chomp[End]
}

#message:2F:(Misc_GiantChompTattle) {
	[Style right]
	This is Giant Chomp.[Wait][End]
}

#message:2F:(Misc_Crate) {
	Crate[End]
}

#message:2F:(Misc_CrateTattle) {
	[Style right]
	This is Crate.[Wait][End]
}

#message:2F:(Misc_ShyGuyRider) {
	Shy Guy Rider[End]
}

#message:2F:(Misc_ShyGuyRiderTattle) {
	[Style right]
	This is Shy Guy Rider.[Wait][End]
}

#message:2F:(Misc_KoopaTheKid) {
	Koopa the Kid[End]
}

#message:2F:(Misc_KoopaTheKidTattle) {
	[Style right]
	This is Koopa the Kid.[Wait][End]
}

#message:2F:(Misc_KoopaGang) {
	Koopa Gang[End]
}

#message:2F:(Misc_KoopaGangTattle) {
	[Style right]
	This is the Koopa Gang.[Wait][End]
}

#message:2F:(Misc_BowserInteract) {
	[Style right]
	[Voice bowser]
	Gwaah ha ha ha ha ha!!!!![BR][Wait][End]
}
