#message:2F:(Misc_GreenBandit)
{
	G Bandit[End]
}










#message:2F:(Misc_GreenBanditTattle)
{
	[Style right]
	This is Green Bandit.[Wait][End]
}










#message:2F:(Misc_YellowBandit)
{
	Y Bandit[End]
}










#message:2F:(Misc_YellowBanditTattle)
{
	[Style right]
	This is Yellow Bandit.[Wait][End]
}










#message:2F:(Misc_BlackBandit)
{
	B Bandit[End]
}










#message:2F:(Misc_BlackBanditTattle)
{
	[Style right]
	This is Black Bandit.[Wait][End]
}










#message:2F:(Misc_RedBandit)
{
	R Bandit[End]
}










#message:2F:(Misc_RedBanditTattle)
{
	[Style right]
	This is Red Bandit.[Wait][End]
}










#message:2F:(Misc_BrigaderBones)
{
	Brigader Bones[End]
}










#message:2F:(Misc_BrigaderBonesTattle)
{
	[Style right]
	This is Brigader Bones.[Wait][End]
}










#message:2F:(Misc_GiantChomp)
{
	Giant Chomp[End]
}










#message:2F:(Misc_GiantChompTattle)
{
	[Style right]
	This is Giant Chomp.[Wait][End]
}










#message:2F:(Misc_Crate)
{
	Crate[End]
}










#message:2F:(Misc_CrateTattle)
{
	[Style right]
	This is Crate.[Wait][End]
}










#message:2F:(Misc_ShyGuyRider)
{
	Shy Guy Rider[End]
}










#message:2F:(Misc_ShyGuyRiderTattle)
{
	[Style right]
	This is Shy Guy Rider.[Wait][End]
}










#message:2F:(Misc_KoopaTheKid)
{
	Koopa the Kid[End]
}










#message:2F:(Misc_KoopaTheKidTattle)
{
	[Style right]
	This is Koopa the Kid.[Wait][End]
}










#message:2F:(Misc_KoopaGang)
{
	Koopa Gang[End]
}










#message:2F:(Misc_KoopaGangTattle)
{
	[Style right]
	This is the Koopa Gang.[Wait][End]
}










#message:2F:(Misc_BowserInteract)
{
	[Style right]
	[Voice bowser]
	Gwaah ha ha ha ha ha!!!!![BR][Wait][End]
}









#message:2F:(Misc_PeachInteract)
{
[Style Right]Hi Mario how can I help you?[BR][WAIT][END]
}









#message:2F:(Misc_ItemTip)
{
	Item[End]
}









#message:2F:(Misc_MenuBuy)
{
	Buy which one?[End]
}







#message:2F:(Misc_BuyToad1)
{
	[Style right]
	There isn't much left Mario.[BR]
	[Wait][Next]
	Just place your coins on the[BR]
	counter.[BR]
	[Wait][Next]
	So do you want to buy a Item?[BR]
	[Yield][End]
}







#message:2F:(Misc_BuyToad2)
{
	[Style right]
	You want to buy[BR]
	"[Var 0]" for[BR]
	[Var 1] Coins.[BR]
	[Wait][Next]
	Is this what you want?[BR]
	[Yield][End]
}







#message:2F:(Misc_BuyToad3)
{
	[Style right]
	Do you want to buy more?[BR]
	[Yield][End]
}







#message:2F:(Misc_BuyToad4)
{
	[Next]
	Goodbye![BR]
	[Wait][End]
}






#message:2F:(Misc_BuyToad5)
{
	[Next]
	Mario...[BR]
	[Pause 10]You don't have any Star Pieces.[BR]
	[Pause 10]Sorry, then. No can do.
	[Wait][End]
}






#message:2F:(Misc_BuyToad6)
{
	[Style right]
	Apologies Mario.[BR]
	[Wait][Next]
	But I don't have any more[BR]
	Items to sell to you.[BR]
	[Pause 10]Good luck Mario!
	[Wait][End]
}





#message:2F:(Misc_BuyToad7)
{
[Next]
Which Items do you want to buy?[BR]
[Wait][End]
}





#message:2F:(Misc_BuyToad8)
{
[Style right]
Changed your mind eh?[BR]
[Pause 10]I gotcha.[BR]
[Wait][End]
}




#message:2F:(Misc_BuyToad9)
{
[Style right]
You want to buy[BR]
"[Var 0]" for[BR]
[Var 1] Star Pieces.[BR]
[Wait][Next]
Is this what you want?[BR]
[Yield][End]
}




#message:2F:(Misc_BuyToad10)
{
[Next]
Changed your mind eh?[BR]
[Pause 10]Take your time.[BR]
[Wait][Next]
Alright. Do you want to buy a[BR]
different Item?[BR]
[Wait][End]
}



#message:2F:(Misc_BuyToad11)
{
[Style right]
Thanks for shopping here Mario![BR]
[Wait][End]
}



#message:2F:(Misc_BuyToad12)
{
[Style right]
Ok Mario.[BR]
[Pause 10]I still have some leftovers.[BR]
[Yield][End]
}



#message:2F:(Misc_BuyToad13)
{
[Next]
You don't want anymore[BR]
leftovers?[BR]
[Wait][Next]
Well. That's fine! I can probably[BR]
sell the rest later.[BR]
[Wait][Next]
Please feel free to shop with me[BR]
later.
[Wait][End]
}








#message:2F:(Misc_BuyTayceT1)
{
	[Style right]
	There isn't much left Mario.[BR]
	[Wait][Next]
	Just place your coins on the[BR]
	counter.[BR]
	[Wait][Next]
	So do you want to buy a Item?[BR]
	[Yield][End]
}







#message:2F:(Misc_BuyTayceT2)
{
	[Style right]
	You want to buy[BR]
	"[Var 0]" for[BR]
	[Var 1] Coins.[BR]
	[Wait][Next]
	Is this what you want?[BR]
	[Yield][End]
}







#message:2F:(Misc_BuyTayceT3)
{
	[Style right]
	Do you want to buy more?[BR]
	[Yield][End]
}







#message:2F:(Misc_BuyTayceT4)
{
	[Next]
	Goodbye![BR]
	[Wait][End]
}






#message:2F:(Misc_BuyTayceT5)
{
	[Next]
	Mario...[BR]
	[Pause 10]You don't have any Coins.[BR]
	[Pause 10]Sorry, then. No can do.
	[Wait][End]
}






#message:2F:(Misc_BuyTayceT6)
{
	[Style right]
	Apologies Mario.[BR]
	[Wait][Next]
	But I don't have any more[BR]
	Items to sell to you.[BR]
	[Pause 10]Good luck Mario!
	[Wait][End]
}





#message:2F:(Misc_BuyTayceT7)
{
[Next]
Which Items do you want to buy?[BR]
[Wait][End]
}





#message:2F:(Misc_BuyTayceT8)
{
[Style right]
Changed your mind eh?[BR]
[Pause 10]I gotcha.[BR]
[Wait][End]
}




#message:2F:(Misc_BuyTayceT9)
{
[Style right]
You want to buy[BR]
"[Var 0]" for[BR]
[Var 1] Coins.[BR]
[Wait][Next]
Is this what you want?[BR]
[Yield][End]
}




#message:2F:(Misc_BuyTayceT10)
{
[Next]
Changed your mind eh?[BR]
[Pause 10]Take your time.[BR]
[Wait][Next]
Alright. Do you want to buy a[BR]
different Item?[BR]
[Wait][End]
}



#message:2F:(Misc_BuyTayceT11)
{
[Style right]
Thanks for shopping here Mario![BR]
[Wait][End]
}



#message:2F:(Misc_BuyTayceT12)
{
[Style right]
Ok Mario.[BR]
[Pause 10]I still have some leftovers.[BR]
[Yield][End]
}



#message:2F:(Misc_BuyTayceT13)
{
[Next]
You don't want anymore[BR]
leftovers?[BR]
[Wait][Next]
Well. That's fine! I can probably[BR]
sell the rest later.[BR]
[Wait][Next]
Please feel free to shop with me[BR]
later.
[Wait][End]
}
