#message:2F:(Misc_GreenBandit)
{
G Bandit[End]
}







#message:2F:(Misc_GreenBanditTattle)
{
[Style right]
This is Green Banditkoopa.[BR]
[Pause 10]This guy's sitting on a massive[BR]
Biff Cannon![BR]
[Wait][Next]
Max HP: 15, Attack Power: 1,[BR]
Defense Power: 1[BR]
[Wait][Next]
That thing looks like it can[BR]
fire very fast, I hear it[BR]
humming from here![BR]
[Wait][Next]
We should find a way to power[BR]
it down, we have enough firepower[BR]
to deal with already![BR]
[Wait][End]
}







#message:2F:(Misc_YellowBandit)
{
Y Bandit[End]
}







#message:2F:(Misc_YellowBanditTattle)
{
[Style right]
This is Yellow Banditkoopa.[BR]
[Wait][Next]
He's hiding behind a Chomp?[BR]
What a coward!![BR]
[Wait][Next]
Max HP: 15, Attack Power: 1,[BR]
Defense Power: 1[BR]
[Wait][Next]
I don't think you're going to[BR]
be able to fight him if his[BR]
guard dog is watching you.[BR]
[Wait][Next]
Maybe there's a way to stun[BR]
the Chomp and get to him...[BR]
[Wait][End]
}







#message:2F:(Misc_BlackBandit)
{
B Bandit[End]
}







#message:2F:(Misc_BlackBanditTattle)
{
[Style right]
This is Black Banditkoopa.[BR]
[Pause 10]W-what's he got in his hands?![BR]
[Wait][Next]
Max HP: 15, Attack Power: 1,[BR]
Defense Power: 1[BR]
[Wait][Next]
This guy definitely came[BR]
prepared, it doesn't look[BR]
like you can get to him with[BR]
those boxes in the way.[BR]
[Wait][Next]
We need to deal with those[BR]
blockades quick![BR]
We're sitting ducks here![BR]
[Wait][End]
}







#message:2F:(Misc_RedBandit)
{
R Bandit[End]
}









#message:2F:(Misc_RedBanditTattle)
{
[Style right]
This is Red Banditkoopa.[BR]
[Pause 10]He's the fourth one[BR]
you've seen now.[BR]
[Wait][Next]
It looks like there's a[BR]
box of bombs underneath him,[BR]
that's scary![BR]
[Wait][Next]
Max HP: 15, Attack Power: 1,[BR]
Defense Power: 1[BR]
[Wait][Next]
I think he's just going to toss[BR]
things at us, this seems like a[BR]
last resort to me.[BR]
[Wait][Next]
[Pause 10]...Who knows if there's more[BR]
than bombs in there?[BR]
Just be careful![BR]
[Wait][End]
}






#message:2F:(Misc_BuzzyBeetleTattle)
{
[Style right]
This is a Buzzy Beetle.[BR]
[Pause 10]Buzzy Beetles are cute--[BR]
but mean.[BR]
[Wait][Next]
Max HP: 3, Attack Power: 2,[BR]
Defense Power: 2[BR]
[Wait][Next]
It looks like this one is powering[BR]
the cannon Green is using.[BR]
[Wait][Next]
We should take him out and[BR]
power down the cannon,[BR]
those shots hurt![BR]
[Wait][Next]
[Pause 10]Keep flipping 'em, Mario![BR]
[Wait][End]
}




#message:2F:(Misc_BrigaderBones)
{
Brigader Bones[End]
}







#message:2F:(Misc_BrigaderBonesTattle)
{
[Style right]
This is a Brigader Bones.[BR]
[Pause 10]These guys are skeletal[BR]
remains of army deserters.[BR]
[Wait][Next]
Max HP: 8, Attack Power: 4,[BR]
Defense Power: 2[BR]
[Wait][Next]
These guys aren't going to[BR]
stay down when you beat them,[BR]
they are tough soldiers![BR]
[Wait][Next]
If you want to stop that[BR]
Howitzer Hal for good,[BR]
I think you're going to have[BR]
to blow them sky-high![BR]
[Wait][End]
}







#message:2F:(Misc_GiantChomp)
{
Giant Chomp[End]
}







#message:2F:(Misc_GiantChompTattle)
{
[Style right]
It's a Chomp![BR]
[Pause 10]A very large one at that![BR]
[Wait][Next]
Max HP: 4, Attack Power: 3,[BR]
Defense Power: 3[BR]
[Wait][Next]
We aren't getting anywhere near[BR]
Yellow with this guy in the way...[BR]
[Wait][Next]
We should find a way to[BR]
incapacitate him, I think[BR]
he'll maul you if you lay[BR]
a hand on himself![BR]
[Wait][End]
}



#message:2F:(Misc_HammerBrosTattle)
{
[Style right]
These are the Hammer Bros.[BR]
[Pause 10]You've seen these punks[BR]
before, haven't you?[BR]
[Wait][Next]
Max HP: 12, Attack Power: 5,[BR]
Defense Power: 1[BR]
[Wait][Next]
Be careful of that hammer![BR]
If it hits you, you'll get[BR]
shrunk in a wink.[BR]
[Wait][Next]
I hear they change up their[BR]
strategies often, don't expect[BR]
them all to attack the same![BR]
[Wait][Next]
As always, they're not to be[BR]
underestimated.[BR]
[Wait][End]
}




#message:2F:(Misc_Crate)
{
Crate[End]
}







#message:2F:(Misc_CrateTattle)
{
[Style right]
This is a Crate[BR]
[Pause 10]When did these get here?[BR]
[Wait][Next]
Max HP: ???, Attack Power: 0,[BR]
Defense Power: 0[BR]
[Wait][Next]
These things are[BR]
blocking our way,[BR]
this is a big problem.[BR]
[Wait][Next]
All boxes have a way of[BR]
being broken, we have to[BR]
find a way to get rid of[BR]
them, and fast![BR]
[Wait][End]
}







#message:2F:(Misc_ShyGuyRider)
{
Shy Guy Rider[End]
}







#message:2F:(Misc_ShyGuyRiderTattle)
{
[Style right]
This is Shy Guy Rider.[Wait][End]
}



#message:2F:(Misc_PyroGuyTattle)
{
[Style right]
This is a Pyro Guy.[BR]
[Pause 10]Pyro Guys are on fire, so any[BR]
contact with them will cause[BR]
damage.[BR]
[Wait][Next]
Max HP: 10, Attack Power: 0,[BR]
Defense Power: 0[BR]
[Wait][Next]
Does this guy know he's in a[BR]
battle? He looks like he's on[BR]
vacation![BR]
[Wait][Next]
...[Pause 10]I guess he won't give us[BR]
any trouble, should we beat him?[BR]
[Wait][End]
}




#message:2F:(Misc_KoopatheKid)
{
Koopa the Kid[End]
}







#message:2F:(Misc_KoopatheKidTattle)
{
[Style right]
It's Koopa the Kid![BR]
[Pause 10]He's a lot scarier in person![BR]
[Wait][Next]
Max HP: 30, Attack Power: 4,[BR]
Defense Power: 0[BR]
[Wait][Next]
It looks like he's preparing a[BR]
big attack with his Gang.[BR]
[Wait][Next]
Focus on Banditkoopas and make[BR]
sure he can't use them against[BR]
you![BR]
[Wait][Next]
He might have other tricks up his[BR]
sleeves too, so keep an eye out!
[Wait][End]
}







#message:2F:(Misc_KoopaGang)
{
Koopa Gang[End]
}







#message:2F:(Misc_KoopaGangTattle)
{
[Style right]
This is the Koopa Gang.[Wait][End]
}







#message:2F:(Misc_BowserInteract)
{
[Style right]
[Voice bowser]
Gwaah ha ha ha ha ha!!!!![BR][Wait][End]
}







#message:2F:(Misc_CutsceneTest)
{
[Style Right]
Test.[BR]
[Wait][End]
}




#message:2F:(Misc_ToadsworthInteract)
{
[Style Right]
Have you made your[BR]
preparations, Master Mario?[BR]
[Wait][End]
}



#message:2F:(Misc_ToadsworthInteractNo)
{
[Style Right]
You must hurry Master Mario![BR]
Every moment the princess[BR]
is unsafe, we risk certain doom![BR]
[Wait][End]
}



#message:2F:(Misc_ToadsworthInteractYes)
{
[Style Right]
Excellent! Make haste[BR]
and venture forth![BR]
[Wait][End]
}



#message:2F:(Misc_ToadsworthStartBoss)
{
[Style Right]
Quickly now! Tally-ho! Early[BR]
buzzard gets the spoils! You've[BR]got this! Protect the princess![BR]
[Wait][End]
}



#message:2F:(Misc_BubbaInteract)
{
[Style Right]
She told me that I would be in[BR]
the pan 10 minutes ago![BR]
[Wait][Next]
Unbelievable.
[Wait][End]
}







#message:2F:(Misc_ToadMinisterInteract)
{
[Style Right]
I have faith in you Mario,[BR]
oust those ne'er-do-wells![BR]
[Wait][Next]
I'll stay here and keep the lunch[BR]
safe and sound.[BR]
[Wait][End]
}



#message:2F:(Misc_LuigiInteract)
{
[Style Inspect]
He's in a deep sleep, not even[BR]
the dead could wake him.[BR]
[Wait][End]
}




#message:2F:(Misc_KammyInteract)
{
[Style Right]
Nyeah heh heh... not so fast![BR]
[Pause 5]Turn around nice and slowly...[BR]
[Wait][Next]
You don't want to know what[BR]
I'm packing in here![BR]
[Wait][End]
}







#message:2F:(Misc_PeachInteract)
{
[Style Right]
Hi Mario how can I help you?[BR]
[Wait][End]
}





#message:2F:(Misc_TrainHeistMapTattle)
{
[Style tattle]
[EnableCDownNext]I can't believe they found us here,[BR]
I guess even a trip on Steamer[BR]
isn't discreet enough...[BR]
[Wait][Next]
It's so nice in here though, it almost[BR]
makes me forget about the[BR]
danger outside.[BR]
[Wait][End]
}




#message:2F:(Misc_TayceTTattle)
{
[Style tattle]
[EnableCDownNext]She's Tayce T., by far the[BR]
greatest cook around.[BR]
[Wait][Next]
It seems like she's really busy[BR]
right now though...[BR]
[Pause 10]Maybe she can still help us?[BR]
[Wait][End]
}





#message:2F:(Misc_CalamityKammyTattle)
{
[Style tattle]
[EnableCDownNext]That's Calamity Kammy, the nastiest[BR]
sharpshooter in the Koopa Gang![BR]
[Wait][Next]
I heard she taught Koopa the Kid[BR]
all he knows about firepower.[BR]
[Wait][Next]
I wouldn't mess with her right now,[BR]
let's just walk away.[BR]
[Wait][End]
}





#message:2F:(Misc_BigBubbaTattle)
{
[Style tattle]
[EnableCDownNext]That's a.. Big Bubba?! [BR]
What's he doing all the way out here?[BR]
[Wait][Next]
Hm...[Pause 10] Well I guess as long as he's[BR]
not hungry we don't have to[BR]
worry, we're safe.[BR]
[Wait][End]
}





#message:2F:(Misc_ToadMinisterTattle)
{
[Style tattle]
[EnableCDownNext]This is the Toad Minister.[BR]
[Wait][Next]
Uh...[Pause 10] he doesn't seem too concerned[BR]
with the situation outside.[BR]
[Wait][Next]
I haven't seen him eat since we left,[BR]
he must be pretty hungry right now.[BR]
[Wait][End]
}





#message:2F:(Misc_LuigiTattle)
{
[Style tattle]
[EnableCDownNext]He's Luigi.[BR]
[Pause 5]I don't have to say anything[BR]
about him, do I? He's your[BR]
brother![BR]
[Wait][Next]
...[Pause 10]He should be helping us[BR]
though, shouldn't he?[BR]
[Wait][End]
}





#message:2F:(Misc_PeachTattle)
{
[Style tattle]
[EnableCDownNext]Come on Mario, you know who[BR]
Princess Peach is![BR]
[Wait][Next]
[Pause 10]...Oh? Maybe you're testing me[BR]
right now?[BR]
[Wait][Next]
I'm happy to play along[BR]
but we really should be getting[BR]
ready right now.[BR]
[Wait][End]
}





#message:2F:(Misc_ToadTattle)
{
[Style tattle]
[EnableCDownNext]That's Toad, he's been traveling[BR]
with the princess for a while now. [BR]
[Wait][Next]
It's his responsibility to watch the[BR]
Badge shipment being delivered.[BR]
[Wait][Next]
He should be alright with you[BR]
borrowing some, go ahead and ask![BR]
[Wait][End]
}





#message:2F:(Misc_ToadsworthTattle)
{
[Style tattle]
[EnableCDownNext]That's Toadsworth, he's been with[BR]
the princess for years as[BR]
her steward.[BR]
[Wait][Next]
He's very adamant about ensuring[BR]
the safety and security of the[BR]
princess at all times.[BR]
[Wait][Next]
I would stop staring at him and[BR]
get ready, he's looking very worried[BR]
at the moment.[BR]
[Wait][End]
}










#message:2F:(Misc_ItemTip)
{
Item[End]
}







#message:2F:(Misc_MenuBuy)
{
Buy which one?[End]
}







#message:2F:(Misc_BorrowToad1)
{
	[Style right]
	Mario! Are you really going out[BR]
	there? You should take some of[BR]
	these badges we're delivering,[BR]
	they could really come in handy![BR]
	[Wait][Next]
	Just leave some Star Pieces[BR]
	with me just in case something[BR]
	happens to them out there if you[BR]
	don't mind.[BR]
	[Wait][Next]
	Will you borrow some badges?[BR]
	[Yield][End]
}







#message:2F:(Misc_BorrowToad2)
{
	[Style right]
	You want to take[BR]
	"[Var 0]" for[BR]
	[Var 1] Star Pieces.[BR]
	[Wait][Next]
	Is this what you want?[BR]
	[Yield][End]
}







#message:2F:(Misc_BorrowToad3)
{
	[Style right]
	Do you want to borrow more?[BR]
	[Yield][End]
}







#message:2F:(Misc_BorrowToad4)
{
	[Next]
	Good luck! Don't forget to equip[BR]
	any badges you have![BR]
	[Wait][End]
}







#message:2F:(Misc_BorrowToad5)
{
	[Next]
	Sorry Mario...[BR]
	[Pause 10]You don't have any Star Pieces.[BR]
	[Pause 10]It's just too risky, I'm sure you'll[BR]
	do fine out there...
	[Wait][End]
}







#message:2F:(Misc_BorrowToad6)
{
	[Style right]
	Sorry Mario.[BR]
	[Wait][Next]
	But I don't have any more[BR]
	Badges to lend to you.[BR]
	[Pause 10]Good luck![BR]
	[Wait][End]
}







#message:2F:(Misc_BorrowToad7)
{
[Next]
Which Badges do you want to[BR]
borrow?[BR]
[Wait][End]
}







#message:2F:(Misc_BorrowToad8)
{
[Style right]
Changed your mind eh?[BR]
[Pause 10]No problem![BR]
[Wait][End]
}







#message:2F:(Misc_BorrowToad9)
{
[Style right]
You want to borrow[BR]
"[Var 0]" for[BR]
[Var 1] Star Pieces.[BR]
[Wait][Next]
Is this what you want?[BR]
[Yield][End]
}







#message:2F:(Misc_BorrowToad10)
{
[Next]
Changed your mind huh?[BR]
[Pause 10]Take your time.[BR]
[Wait][Next]
Alright. Do you want to borrow a[BR]
different Badge?[BR]
[Wait][End]
}







#message:2F:(Misc_BorrowToad11)
{
[Style right]
Good choice Mario![BR]
[Wait][End]
}







#message:2F:(Misc_BorrowToad12)
{
[Style right]
Mario.[BR]
[Pause 10]I still have some Badges.[BR]
You could borrow.[BR]
[Yield][End]
}







#message:2F:(Misc_BorrowToad13)
{
[Next]
You don't want to borrow more[BR]
Badges?[BR]
[Wait][Next]
No problem! The less risk for me,[BR]
the better![BR]
[Wait][Next]
Although you can borrow more[BR]
if you want to...[BR]
[Wait][End]
}







#message:2F:(Misc_BuyTayceT1)
{
	[Style right]
	Oh, hi there Mario! [HEART][BR]
	[Wait][Next]
	I'm terribly busy at the moment,[BR]
	I'm afraid I can't cook you[BR]
	anything![BR]
	[Wait][Next]
	Would you like to look through the[BR]
	day's leftovers?[BR]
	[Yield][End]
}







#message:2F:(Misc_BuyTayceT2)
{
	[Style right]
	You want to take[BR]
	"[Var 0]" for[BR]
	[Var 1] Coins.[BR]
	[Wait][Next]
	Do you want this one?[BR]
	[Yield][End]
}







#message:2F:(Misc_BuyTayceT3)
{
	[Style right]
	Do you want to buy more?[BR]
	[Yield][End]
}







#message:2F:(Misc_BuyTayceT4)
{
	[Next]
	Goodbye! Be careful and eat[BR]
	slowly![HEART][BR]
	[Wait][End]
}







#message:2F:(Misc_BuyTayceT5)
{
	[Next]
	Sorry Mario...[BR]
	[Pause 10]You don't have any Coins.[BR]
	[Pause 10]I can't give both you and your[BR]
	brother a tab today.[BR]
	[Wait][End]
}







#message:2F:(Misc_BuyTayceT6)
{
	[Style right]
	I'm sorry Mario![BR]
	[Wait][Next]
	But we don't have any more[BR]
	leftovers at the moment.[BR]
	[Pause 10]Good luck Mario!
	[Wait][End]
}







#message:2F:(Misc_BuyTayceT7)
{
[Next]
Which leftovers do you want to[BR]
take?[BR]
[Wait][End]
}







#message:2F:(Misc_BuyTayceT8)
{
[Style right]
Not your taste huh?[BR]
[Pause 10]It's okay I understand.[BR]
[Wait][End]
}







#message:2F:(Misc_BuyTayceT9)
{
[Style right]
You want to buy[BR]
"[Var 0]" for[BR]
[Var 1] Coins.[BR]
[Wait][Next]
Is this what you want?[BR]
[Yield][End]
}







#message:2F:(Misc_BuyTayceT10)
{
[Next]
Changed your mind huh?[BR]
[Pause 10]Take your time.[BR]
[Wait][Next]
Alright. Do you want to buy a[BR]
different leftover?[BR]
[Wait][End]
}







#message:2F:(Misc_BuyTayceT11)
{
[Style right]
Thanks for shopping here[BR]
Mario! [HEART][BR]
[Wait][End]
}







#message:2F:(Misc_BuyTayceT12)
{
[Style right]
Oh Mario![BR]
[Pause 10]I still have some leftovers.[BR]
[Yield][End]
}







#message:2F:(Misc_BuyTayceT13)
{
[Next]
You don't want anymore[BR]
leftovers?[BR]
[Wait][Next]
Well. That's fine! I can probably[BR]
sell the rest later.[BR]
[Wait][Next]
Please feel free to shop with me[BR]
anytime!
[Wait][End]
}
