#ifndef _BANDITS_YELLOW_COMMON_H_
#define _BANDITS_YELLOW_COMMON_H_

enum N(BattleCommon) {
    ACTOR_YELLOW_BANDIT       = ACTOR_ENEMY0,
    ACTOR_HAMMER_BRO          = ACTOR_ENEMY1,
    ACTOR_GIANT_CHOMP         = ACTOR_ENEMY2,
};

#endif // _BANDITS_YELLOW_COMMON_H_
